### ISSUE TITLE
Install via Scoop

### ISSUE THREAD

**Issue by wenmin92** [alesimula/wsa_pacman#10]
[Scoop](https://scoop.sh/) is a famous Windows package manager, we can use scoop to install & update wsa_pacman.

Once added to the scoop bucket, we can install and update it like this:
```
scoop install wsa-pacman
```
```
scoop update wsa-pacman
```

Installation and updates will be a breeze.

**Comment by alesimula** [comment]
Does it handle file associations though?

Or dependencies? In case it does, it needs Visual C++ redistributable as a dependency, otherwise I might need to add the DLLs to the portable zip

**Comment by wenmin92** [comment]
> Does it handle file associations though?

Not yet, but we can add scripts in the manifest to handle file associations.

> Or dependencies? In case it does, it needs Visual C++ redistributable as a dependency, otherwise I might need to add the DLLs to the portable zip

Scoop supports adding dependencies, but which version of Visual C++ does this app depend on?

**Comment by alesimula** [comment]
The flutter desktop documentation doesn't seem to specify the version but it says it needs these files specifically

```
msvcp140.dll
vcruntime140.dll
vcruntime140_1.dll
````

**Comment by wenmin92** [comment]
> The [flutter desktop documentatio](https://docs.flutter.dev/desktop)n doesn't seem to specify the version but it says it needs these files specifically

Note [here](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist ):
> However, the version of the Microsoft Visual C++ redistributable installed on the machine must be the same or higher than the version of the Visual C++ toolset used to create your application.

Since flutter requires Visual Studio 2019 to be installed, the vcredist version here should be at least 2019.

**Comment by alesimula** [comment]
@wenmin92 doesn't the vcredist scoop package install the latest version?

**Comment by wenmin92** [comment]
> doesn't the vcredist scoop package install the latest version?

No, each version of vcredist has a separate manifest, and we can choose to install any version.

**Comment by alesimula** [comment]
@wenmin92 

What about [this one?](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist.json)

The exe which the "url" points to seems to be the same all-in-one installer I bundle in my installer (as per screenshot)

![image](https://user-images.githubusercontent.com/3057584/147366087-efe69f0f-44f9-4c99-99bd-82c7eae034ee.png)

**Comment by wenmin92** [comment]
> What about [this one?](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist.json)
> 
> The exe which the "url" points to seems to be the same all-in-one installer I bundle in my installer (as per screenshot)
> 
> ![image](https://user-images.githubusercontent.com/3057584/147366087-efe69f0f-44f9-4c99-99bd-82c7eae034ee.png)

Oh, I'm sorry, I didn't know this package existed, this is certainly better.

**Comment by wenmin92** [comment]
> @wenmin92
> 
> What about [this one?](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist.json)

This is not recommended because it depends on vcredist 2005 ~ 2013, causing these vcredist versions to be installed before installing it, which we don't need.

**Comment by alesimula** [comment]
@wenmin92 What about [this one?](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist2022.json), seems to only install the 2015-2022

**Comment by wenmin92** [comment]
> @wenmin92 What about [this one?](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist2022.json), seems to only install the 2015-2022

Okay, then this one.

**Comment by wenmin92** [comment]
It has been added to scoop's extras bucket, and now we can use scoop to install wsa-pacman. 🎉
