### ISSUE TITLE
[BUG] Install apk successful, but return UNKNOWN_ERROR

### ISSUE THREAD

**Issue by Yukari316** [alesimula/wsa_pacman#103]
version: 1.3.6
windows version: Windows 11, OS Build 10.0.22621.674
WSA version: 2209.40000.26.0
![KXGQP4APR6%OUA% R@9PUB7](https://user-images.githubusercontent.com/7535224/199730704-5bec018f-9e22-4229-a2b9-ac9b132b828d.png)
![image](https://user-images.githubusercontent.com/7535224/199731170-cd1bb6d4-4c70-423b-86fc-40291dda0d91.png)

**Comment by YipSzeho** [comment]
I had the same problem
version: 1.3.6
windows version: 22621.819
WSA version: 2210.40000.7.0

**Comment by alesimula** [comment]
Currently the application waits for the adb installation process for 30 seconds, after which it times out (but it may still be running in the background, so it probably just took more than 30 seconds to install).

Maybe I should have a specific message when for installation timeout, and allow the wait time to be customizable

**Comment by alesimula** [comment]
On version 1.4.0 I added a customisable timeout value (expressed in seconds, + option to disable it) as well as a TIMEOUT status in the installer
