### ISSUE TITLE
The "install" button is greyed out and won't allow me to click it when I tried to install an apk

### ISSUE THREAD

**Issue by vanessabluellie** [alesimula/wsa_pacman#108]
Hello,

I was able to successfully install WSA Pacman, but when I tried to install an apk and a pop-up appeared (I'm assuming to ask that I grant it permission to storage and the like), it **won't allow me to click "install"** because the button is greyed out. I'm not sure where I went wrong... Apologies for the inconvenience, and thank you for any help!

Please refer to this image:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/55352222/205308076-69069f26-511f-490a-92f6-f268125d5351.png">

**Comment by bboehmei** [comment]
Turn on developer settings in windows. Search, settings, developer settings, developer mode > on.

**Comment by vanessabluellie** [comment]
> Turn on developer settings in windows. Search, settings, developer settings, developer mode > on.

Hello, I tried turning developer mode on and then even restarted my laptop. But the Install button is still greyed out...

**Comment by alesimula** [comment]
@vanessabluellie is WSA turned on? it turns off by default when you are not using it (eg. you just started your PC and haven't opened any Android app, or it closes automatically after some minutes if all Android apps have been closed), you can turn WSA on by opening any Android app, there is also a button to to turn it on in the main WSA PacMan interface

![image](https://user-images.githubusercontent.com/3057584/206997870-0d73ece2-cfe8-4fce-a7a7-3616986f5eaf.png)

BTW you can override the automatic Android shut-off from Windows Subsystem for Android Settings, but I don't recommend it as it is very resource-hungry

**Comment by jojoyee** [comment]
> Hello,
> 
> I was able to successfully install WSA Pacman, but when I tried to install an apk and a pop-up appeared (I'm assuming to ask that I grant it permission to storage and the like), it **won't allow me to click "install"** because the button is greyed out. I'm not sure where I went wrong... Apologies for the inconvenience, and thank you for any help!
> 
> Please refer to this image:
> 
> <img alt="image" width="367" src="https://user-images.githubusercontent.com/55352222/205308076-69069f26-511f-490a-92f6-f268125d5351.png">

In Windows Subsystem for Androids settings, after setting Developer options on, click Manage developer settings, set USB debugging on and change Default USB connection to "File Transfer". This works for me.

**Comment by alesimula** [comment]
@jojoyee Hmm, that should not affect it in any way; what happens when you change it back from "File Transfer" to the default one?

**Comment by vanessabluellie** [comment]
> by opening any Android app

WSA is turned off and I tried to press "Turn On" several times, but it would only say "Starting, please stand by" before almost immediately going back to "Arrested, WSA is turned off" :(

**Comment by vanessabluellie** [comment]
> > Hello,
> > I was able to successfully install WSA Pacman, but when I tried to install an apk and a pop-up appeared (I'm assuming to ask that I grant it permission to storage and the like), it **won't allow me to click "install"** because the button is greyed out. I'm not sure where I went wrong... Apologies for the inconvenience, and thank you for any help!
> > Please refer to this image:
> > <img alt="image" width="367" src="https://user-images.githubusercontent.com/55352222/205308076-69069f26-511f-490a-92f6-f268125d5351.png">
> 
> In Windows Subsystem for Androids settings, after setting Developer options on, click Manage developer settings, set USB debugging on and change Default USB connection to "File Transfer". This works for me.

Actually about this, I went into Developer settings of the Windows Subsystem for Android and clicked on "Manage developer settings" so many times, but nothing ever popped up for me so I honestly can't change any of the developer settings at all...

**Comment by karner** [comment]
I had the same issue. 
But when deactivating USB debugging and reactivating it again, I got a gray window prompting me to allow ADB debugging, showing the computer's RSA key fingerprint.
Allowing this fixed it for me. Unfortunately, the setting is enabled by default, but the USB debugging authorization doesn't seem to be given by default.

**Comment by quartzbear** [comment]
> But when deactivating USB debugging and reactivating it again, I got a gray window prompting me to allow ADB debugging, showing the computer's RSA key fingerprint.

This also worked for me. I had already installed one app, but when I tried to install another it wouldn't budge. Your solution works.
Thanks

**Comment by alesimula** [comment]
I have updated WSA PacMan to "solve" this issue.

Now it correctly reports the status as "unauthorized" instead of connected, giving a button to reconnect (might not work because of a WSA bug) and one to open developer settings, from which, as the dialog box explains, you have to turn "USB debugging" off and on again should the first button fail to show a prompt

**Comment by Z2IRIM** [comment]
I found how to go.  go to pacman page, click turn on, if it tells you unanthorized, click the second button, go to setting. Then enable adb debugging in the panel, try to enable those row relative with it. Then done.
