### ISSUE TITLE
Can't install if in Chinese name folder

### ISSUE THREAD

**Issue by Ga2en** [alesimula/wsa_pacman#11]
Can't install if the APK file in Chinese name folder

**Comment by misheu12** [comment]
maybe it's need English name folder...
also, I can't to install apk from folder withe hebrow name.

**Comment by alesimula** [comment]
@Ga2en This seems to be a bug in aapt.exe; however I might have found a few workarounds

**Comment by alesimula** [comment]
@Ga2en [This version](https://mega.nz/file/gp0FVILb#m2wTpzU8h7COtk_qvHUKEXdzKOS-4AP0iCGqIg4tn68) should work for both directories and files with unicode characters. Can you guys confirm this works? (the fix will be released in 1.1.2)

**Comment by Neomanbeta** [comment]
Sadly, it does not work with 1.1.2，the filename is not in Chinese and it's not in a Chinese name folder, but on the installation screen the Chinese APP title cannot display properly. It will install, but the app won't launch and cannot be installed (maybe it wasn't installed properly in the first place?).

**Comment by Ga2en** [comment]
> @Ga2en @misheu12 [This version](https://github.com/alesimula/wsa_pacman/releases/tag/v1.1.2) should work for both directories and files with unicode characters. Can you guys confirm it works?

This version works well

**Comment by Ga2en** [comment]
> Sadly, it does not work with 1.1.2，the filename is not in Chinese and it's not in a Chinese name folder, but on the installation screen the Chinese APP title cannot display properly. It will install, but the app won't launch and cannot be installed (maybe it wasn't installed properly in the first place?).

This new version works well for me, my file is in 下载 folder, please confirm so I can close this issue

**Comment by Neomanbeta** [comment]
> > Sadly, it does not work with 1.1.2，the filename is not in Chinese and it's not in a Chinese name folder, but on the installation screen the Chinese APP title cannot display properly. It will install, but the app won't launch and cannot be installed (maybe it wasn't installed properly in the first place?).
> 
> This new version works well for me, my file is in 下载 folder, please confirm so I can close this issue

I just uninstalled the previous version and reinstall the latest version, it seems to be working now.
