### ISSUE TITLE
Unable to install apks over 1GB in size

### ISSUE THREAD

**Issue by subby2006** [alesimula/wsa_pacman#119]
When double clicking on an apk over 1gb in size, the window prompt to install the apk does not appear. The apk installs just fine through the adb command line

**Comment by alesimula** [comment]
Can you share the apk file's download link?

**Comment by subby2006** [comment]
danganronpa 2 on modyolo.com

**Comment by alesimula** [comment]
@subby2006 Fixed in latest release
