### ISSUE TITLE
Offline: Could not establish a connection with WSA: Either developer mode and USB debuggin are disabled or a wrong port is specified.

### ISSUE THREAD

**Issue by Haiyami** [alesimula/wsa_pacman#121]
So I can't get the pack manager to work. I am using the portable version. It keeps saying: 

**Offline: Could not establish a connection with WSA: Either developer mode and USB debuggin are disabled or a wrong port is specified.**

I'm not sure how to resolve this problem either. I am trying to use this with a hacked version of WSA for windows 10. WSA works on windows 10 but I need a pack manager to install apps. 

https://imgur.com/a/dZ30U5U

https://imgur.com/a/nM09OA0

**Comment by alesimula** [comment]
![image](https://github.com/alesimula/wsa_pacman/assets/3057584/4d2ff7e2-f3c1-42a4-b422-3a41ccd1aea4)
![image](https://github.com/alesimula/wsa_pacman/assets/3057584/3e68c927-ae4e-47dd-b6ae-e3c6bfa9276f)
Did you make sure Developer Mode is enabled?

**Comment by alesimula** [comment]
@Haiyami I updated the application, it now detects the "Partially running" mode as turned off
