### ISSUE TITLE
how do I fix this.

### ISSUE THREAD

**Issue by diskbeta** [alesimula/wsa_pacman#130]
I keep on getting this issue

https://drive.google.com/file/d/12K62Go09nOmebVPl5PSpmssKVQ5gnyJN/view?usp=sharing

**Comment by Mitia99** [comment]
You have to enable developper settings  in WSA

![AddText_09-08-09.18.23.png](https://github.com/alesimula/wsa_pacman/assets/56766778/0413cc03-bc46-430f-a8fb-f243964047b9)
