### ISSUE TITLE
WSA cannot be turned on because of ERROR: this code execution cannot be proceed because gfxstream_backend.dll was not found. Reinstalling the program may fix this problem.

### ISSUE THREAD

**Issue by hamzamaqsood877** [alesimula/wsa_pacman#14]
I also reinstalled the program but still facing the same error.

![image](https://user-images.githubusercontent.com/73820858/147421152-bc426583-2e2e-42fe-adf0-092e570509c3.png)

**Comment by hamzamaqsood877** [comment]
IP address needed to be refreshed from Windows Sub-System for Android (WSA) and all went well.

**Comment by liudonghua123** [comment]
I have the same issue.

![image](https://user-images.githubusercontent.com/2276718/147635913-024356fc-79a3-41bc-bb12-3842c9308930.png)

**Comment by alesimula** [comment]
@liudonghua123 Does [this test version](https://mega.nz/file/Qhk2lKja#Rzg1dnMy5yi2bUMxbgPctzFXVBf-d7FB3oIe0TsbRHk) fix the issue when starting WSA?

**Comment by kylefmohr** [comment]
> @liudonghua123 Does [this test version](https://mega.nz/file/Qhk2lKja#Rzg1dnMy5yi2bUMxbgPctzFXVBf-d7FB3oIe0TsbRHk) fix the issue when starting WSA?

Hi @alesimula, I was having the same issue, and after installing the test version, the error regarding gfxstream_backend.dll no longer shows up. Thanks!

**Comment by alesimula** [comment]
@kylefmohr Great, next update will have this fix

**Comment by JoseCreator1** [comment]
having this same shi
