### ISSUE TITLE
Should change text colour on blue buttons

### ISSUE THREAD

**Issue by Kevin8675** [alesimula/wsa_pacman#16]
Currently all the buttons (install/cancel) have black text. The Install button (or any button that has a blue background) should have a more bright text (probably white) as the text is not really noticeable. 
![image](https://user-images.githubusercontent.com/70042736/147708987-4f153724-bdbb-4c7b-8177-da89191e4cf8.png)

**Comment by alesimula** [comment]
@Kevin8675  A different text color on an adjacent button would look weird, but I'm considering using a lighter accent color for light mode, what do you think? 
![image](https://user-images.githubusercontent.com/3057584/148405999-58d3b704-b609-4138-a860-79c52700b759.png)

**Comment by Kevin8675** [comment]
@alesimula This colour looks a lot better in my opinion.

**Comment by alesimula** [comment]
@Kevin8675 [Here is a test version](https://mega.nz/file/x9lTDY7Y#KWpK6TrQN2UllfU8M500sj551P--0Akx17ygXwvcB8s) if you want to try it (the "WsaClient path" is related to another issue I'm testing)

**Comment by Kevin8675** [comment]
@alesimula I just installed the test version and it looks great! Another minor design issue is that in the settings menu, the switches for autostart and icons are not lined up vertically.
![image](https://user-images.githubusercontent.com/70042736/148416078-a1e6cf34-b305-4c4b-9a5b-85940f071b5c.png)
Even though there is an arrow for the icons, I think the switches should line up.

**Comment by alesimula** [comment]
@Kevin8675 I was trying to follow the Windows settings' fluent UI choices

![image](https://user-images.githubusercontent.com/3057584/148420042-98ffc963-021e-4d77-80e8-d8c83656e6e5.png)

![image](https://user-images.githubusercontent.com/3057584/148420068-fe03edf0-84a1-46c0-808f-e1f5dcf1fab2.png)

**Comment by Kevin8675** [comment]
Ah I see, makes sense.

**Comment by alesimula** [comment]
@Kevin8675 change released in new version
