### ISSUE TITLE
Pacman shows app installed but they aren't.

### ISSUE THREAD

**Issue by PRinceBhai** [alesimula/wsa_pacman#2]
Opening an apk after associating it with pacman I can see the Installer window appear and pacman reads package name and shows it icon but when I click Install it instantly shows me the "App Installed" Window in just a sec. That means the app wasn't installed clicking on "Open App" doesn't do anything because the app isn't Installed. Obviously not visible in Start Menu.

**Comment by alesimula** [comment]
What's the result of running the command "adb devices"?

**Comment by alesimula** [comment]
@PRinceBhai nevermind, I made a stupid mistake... but it should be fixed in the new version, can you confirm?

**Comment by PRinceBhai** [comment]
@alesimula Yep, Apps are installing now. Thanks for the fix! :)
