### ISSUE TITLE
Quick power button does not work

### ISSUE THREAD

**Issue by shlomo-shlomo** [alesimula/wsa_pacman#20]
Thanks for this great software!
But the WSA quick power button does not work for me, I press and it does not turn on the WSA
Only after I open any app is the WSA enabled and then apps can be installed.
with gratitude
Written using Google Translate, I do not speak English.

**Comment by shlomo-shlomo** [comment]
![fiald](https://user-images.githubusercontent.com/78599753/148289750-82113212-1efc-410f-8a80-9ca0dbc61ec3.gif)

**Comment by shlomo-shlomo** [comment]
I press like that 👆👆👆 and nothing happens.

**Comment by shlomo-shlomo** [comment]
@alesimula

**Comment by alesimula** [comment]
@shlomo-shlomo  do you see (even for a moment) the process WsaClient.exe appear in Windows' task manager?

**Comment by shlomo-shlomo** [comment]
> @shlomo-shlomo do you see (even for a moment) the process WsaClient.exe appear in Windows' task manager when you click on the button?

NO.

**Comment by alesimula** [comment]
@shlomo-shlomo Alrighty then... please download [this application version](https://mega.nz/file/x9lTDY7Y#KWpK6TrQN2UllfU8M500sj551P--0Akx17ygXwvcB8s) and tell me what you see in this text box (the text is selectible)

![image](https://user-images.githubusercontent.com/3057584/148409935-65bc4d7e-ac03-41d3-81bf-51b7179d1ef5.png)

**Comment by shlomo-shlomo** [comment]
@alesimula Errors installing the file ...
![image](https://user-images.githubusercontent.com/78599753/148415672-7ce7104a-ae19-4820-b4d9-8ecd847e6617.png)
![image](https://user-images.githubusercontent.com/78599753/148415681-4d7e46a6-8ac3-44dc-b350-574d99b4c7d8.png)

**Comment by alesimula** [comment]
@shlomo-shlomo just skip the file

**Comment by alesimula** [comment]
@shlomo-shlomo I need your feedback, I cannot replicate this issue and no other user reported it

**Comment by shlomo-shlomo** [comment]
@alesimula OK, I installed and opened the software:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/What now?78599753/148682982-7ae16cbf-519e-4696-90f2-0a88fa943376.png">
What now?

**Comment by alesimula** [comment]
Can you confirm that file exists? If so, it's strange that it doesn't boot

BTW when you install WSA with the terminal (eg. When installing the Magisk + GApps version) the installation directory will be the directory where you extracted the files into; it's unrelated to this problem, but I recommend not using the Download folder

**Comment by shlomo-shlomo** [comment]
> Can you confirm that file exists?

YES,
<img width="578" alt="image" src="https://user-images.githubusercontent.com/78599753/148684336-cd370d76-4d0c-4b9e-af56-8c00d6afbd55.png">

---
Is it possible to transfer the WSA location after installation?

**Comment by alesimula** [comment]
@shlomo-shlomo Maybe it's possible if you find all registry entries that point to the application, but I haven't tried.

Anyway, at least now I know how to replicate the issue, I'll try to install WSA with Gapps and Magisk and see if a can solve the problem

**Comment by shlomo-shlomo** [comment]
@alesimula Thanks.
I installed from here https://github.com/LSPosed/MagiskOnWSA

**Comment by alesimula** [comment]
@shlomo-shlomo Wait, I see the last two folders have a different name; Does copying the exact path you see on the app (except the exe) and pasting it on top of the file explorer brings you to the folder? Also what language is that?

**Comment by shlomo-shlomo** [comment]
@alesimula Copying the path brings me to the folder, as you can see in the picture
https://github.com/alesimula/wsa_pacman/issues/20#issuecomment-1008299301
The words are My Computer> Downloads.
The language is Hebrew.
But the path is not in Hebrew because the real directory name is downloads, and it is only displayed in Hebrew.

**Comment by alesimula** [comment]
@shlomo-shlomo Oh, I see, in any case I'll also trying changing the system language just in case that's the problem

**Comment by shlomo-shlomo** [comment]
@alesimula Is there anything new about it? ...

**Comment by alesimula** [comment]
@shlomo-shlomo trying it out right now

**Comment by alesimula** [comment]
@shlomo-shlomo I don't know why, but starting WSA from the app directory won't work (With the Magisk/Gapps version), only starting it from %LOCALAPPDATA%\Microsoft\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe

**Comment by shlomo-shlomo** [comment]
@alesimula I did not really understand what I needed to do so I could use the quick power button for my WSA.

**Comment by alesimula** [comment]
@shlomo-shlomo What I'm trying to point out is starting the WSA's .exe file directly works with the official WSA, but not with the Magisk+Gapps one, I might need to use a workaround and start the executable located in appdata instead (which seems to works)

**Comment by alesimula** [comment]
I'll just write this here to keep track of this issue's possible solutions

`start shell:appsFolder\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe!App`

`explorer.exe wsa://`

**Comment by alesimula** [comment]
@shlomo-shlomo I might have found a workaround, could you confirm the bug is fixed in [this test version? (portable)](https://mega.nz/file/x0VQBTAT#VrVzYuR-0vUnqdbkW82gnuEDGEhW6HUdmeKe5JZM-xw)

**Comment by shlomo-shlomo** [comment]
@alesimula Yes, it works :)
Well done!!

**Comment by alesimula** [comment]
@shlomo-shlomo latest version released with the fix

**Comment by Madrichim-App** [comment]
@alesimula Thank you!
