### ISSUE TITLE
German localization

### ISSUE THREAD

**Issue by akuropka** [alesimula/wsa_pacman#25]
[de.zip](https://github.com/alesimula/wsa_pacman/files/7835505/de.zip)

**Comment by alesimula** [comment]
@akuropka Thanks; BTW I added some new translation entries I had missed before (those starting with "tempname_")

**Comment by alesimula** [comment]
@akuropka Here are the final names for the previously missed entries

```
"settings_option_generic_system": "System",
"settings_option_generic_disabled": "Disabled",

"theme_mode_dark": "Dark",
"theme_mode_light": "Light",
"theme_mica_full": "Full",
"theme_mica_partial": "Partial",
"theme_icon_adaptive_squircle": "Squircle",
"theme_icon_adaptive_circle": "Circle",
"theme_icon_adaptive_rounded_square": "Rounded Square",

"installer_info_version": "Version: {appVersion}",
"installer_info_version_change": "Version: {appVersionOld} => {appVersionNew}",
"installer_info_package": "Package: {appPackage}",
```

**Comment by akuropka** [comment]
[de.zip](https://github.com/alesimula/wsa_pacman/files/7835869/de.zip)

Actually it's a bit difficult to differentiate between "Squircle" and "Rounded Square" and I think just one of the two layouts are good enough...

**Comment by akuropka** [comment]
If any new strings you can let me know through this issue or in any other way...

**Comment by akuropka** [comment]
@alesimula, I did some finetuning to make things sound more smooth within the context. 😉
[de.zip](https://github.com/alesimula/wsa_pacman/files/7846296/de.zip)

**Comment by akuropka** [comment]
@alesimula, attached the reworked file for "dismiss".
[de.zip](https://github.com/alesimula/wsa_pacman/files/7869363/de.zip)

**Comment by akuropka** [comment]
@alesimula, did some minor modifications:
`installer_btn_starting` - I interpret this as WSA is starting and clarified it
`installer_btn_loading` - I did not come across this message yet, does it mean the app is loaded into WSA pacman?

[de.zip](https://github.com/alesimula/wsa_pacman/files/7876800/de.zip)

**Comment by alesimula** [comment]
`installer_btn_loading` is shown while the app information is still being parsed... though that's usually so quick it won't even show up;

`installer_btn_starting` is shown on the installer button when you enable the "Autostart WSA before installation" option and WSA was shut down.

**Comment by akuropka** [comment]
Great, so both fit now better. 😉

**Comment by alesimula** [comment]
@akuropka I think having the ellipsis would still be better though ("Starte WSA..." / "Lade App...")

**Comment by akuropka** [comment]
Yes, thanks for double checking. I was removing them based on the other texts but this is a continuous state and not a button waiting for user input, so...

**Comment by alesimula** [comment]
@akuropka it's just to let the user know he has to wait and an operation is in progress

**Comment by akuropka** [comment]
Yes, that's why `...` should be added, thanks for the hint.

**Comment by akuropka** [comment]
Attached traditional Chinese (`zh_HK`, `zh_SG`, `zh_TW)`.

[zh_TW.zip](https://github.com/alesimula/wsa_pacman/files/7876985/zh_TW.zip)

**Comment by alesimula** [comment]
@akuropka should I map this to every zh localization **_except_** zh_CN?

**Comment by akuropka** [comment]
`zh` should be `zh_CN` simply because more people are using it (this includes `zh_SG`).
Traditional (`zh_TW`) would be also `zh_HK`, `zh_MO`.
I think those are the relevant ones in Windows.
