### ISSUE TITLE
I know this is not the right place but

### ISSUE THREAD

**Issue by fisforfaheem** [alesimula/wsa_pacman#29]
brother I love how u made this with the flutter, can u please teach me or guide me I am new to flutter i wanna build apps and becomeu ur student

**Comment by alesimula** [comment]
I'm not exactly a flutter expert (this is my second app and the first one was [a save file thumbnail editor for a videogame](https://github.com/alesimula/DRONE-drone-thumbnail-editor)) but I can give you some pointers.

In flutter by default you can create a meterial design or cupertino design app (using MaterialApp and CupertinoApp) you can learn a bit from the default app is created when creating a new project or from [one of these samples](https://flutter.github.io/samples); However I used none and used the [fluent UI library (unofficial)](https://pub.dev/packages/fluent_ui) to give an UWP/Windows Settings like feel to my app. I personally think the library is amazing but still has some shortcomings I had to compensate by modifying some of the library's widgets (you can use those if you want); if you want to use this library, I recommend taking a look at the [fluent UI exaple project](https://github.com/bdlukaa/fluent_ui/tree/master/example).

Some other pretty useful library I'd recommend is [shared_value](https://pub.dev/packages/shared_value): flutter uses states to tell whether a widget's state has changed (and it should be rebuilt): by calling the setState method you are basically signaling an UI component should be changed. This is fine when the state is local (relative to the widget you're calling it from), but a global, app-wide state is a bit more messy; this library makes it extremely easy though

**Comment by fisforfaheem** [comment]
Thank you so much! I am a beginner in flutter and want to make it the only thing to make a career in! 

Thanks for so explanation. Also If I would love to be a part(intern/student/dev) for you.

Thanks, Faheem Ahmad
fisforfaheem@gmail.com

**Comment by fisforfaheem** [comment]
Thanks, I am working a project with my friend ( flutter web project ADMIN
SIDE), It's about patients and doctors and CRUD operations etc (for now)
Can you take a look at it for me.. I am having a few issues, If you are you
could guide/help me with that, When free do let me know:

[image: image.png]
I have to implement this I have already some work..but having issues with
CHARTS,and push notification, also some small issues with user creation.

I am using firebase and flutter only



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
01/13/22,
03:00:40 AM

**Comment by alesimula** [comment]
@fisforfaheem never used firebase but I can take a look at it anways if you want, cannot dedicate too much time to it though as I'm also working full-time

**Comment by fisforfaheem** [comment]
https://4ezonedashboard.netlify.app/ here is my app  can u look at it

**Comment by fisforfaheem** [comment]
i can share my github with ua s well
