### ISSUE TITLE
Adding a Hebrew language

### ISSUE THREAD

**Issue by YOSI-COHEN** [alesimula/wsa_pacman#30]
Hello.
Your software is very helpful to us, can I add Hebrew?

**Comment by alesimula** [comment]
Yes, of course; keep in mind you can remove all entries starting with @ exept @@locale (maybe also keep "@locale_desc" to describe the language in english, while "locale_desc" should have the language name in Hebrew)

**Comment by alesimula** [comment]
@YOSI-COHEN BTW keep in mind I still have to fix right-to-left UI (at the moment it kind of works but looks absolutely terrible)

**Comment by alesimula** [comment]
@YOSI-COHEN I fixed the UI for right-to-left languages.

If you don't know how to make a translation, just add a file to the locale folder (You may use [en.arb](https://github.com/alesimula/wsa_pacman/blob/main/locale/en.arb) as a base) or just send the file to me;

**Comment by YOSI-COHEN** [comment]
Hello
I do not know and do not have time to translate.
If you can you will translate
Thanks

**Comment by alesimula** [comment]
@shlomo-shlomo Maybe you could help, if you'd like

**Comment by Madrichim-App** [comment]
@alesimula I would love to try, what should be done?
I see that some lines contain "@" and some do not
I also see a line like this:
`    "@status_subtext_winver_older": {"description": "Only used inside 'status_unsupported_desc', modify taking this in consideration"},
`This word: `description` Do not translate? I'm right?
I would love an explanation.

**Comment by shlomo-shlomo** [comment]
@alesimula I would love to try, what should be done?
I see that some lines contain "@" and some do not
I also see a line like this:
`    "@status_subtext_winver_older": {"description": "Only used inside 'status_unsupported_desc', modify taking this in consideration"},
`This word: `description` Do not translate? I'm right?
I would love an explanation.

**Comment by alesimula** [comment]
@shlomo-shlomo those are like comments that describe the value, so they're not needed: you can safely remove all values starting with @ except @@locale (which is the language tag); I'm also keeping "@locale_desc" on all files, so i can use "locale_desc" to indicate the language name translated to the language itself, and "@locale_desc" is the name of the language in english (so for French, the value of "locale_desc" would be "Française" and its description would have "French [fr_FR]")

**Comment by shlomo-shlomo** [comment]
@alesimula I made a Hebrew language file here:
https://github.com/shlomo-shlomo/wsa_pacman/blob/main/locale/he.arb
If you can make a trial version that contains this, so I can fix some translations I was not sure what to write because I did not know where in the software the string appears.
I would love if you could give credit for the translation; You can give a link here: https://madrichim.ovh/user/Shlomo.

**Comment by alesimula** [comment]
@shlomo-shlomo I will thanks; BTW I see the entries for "status_offline" and "settings_port" are not translated

**Comment by shlomo-shlomo** [comment]
@alesimula I did not translate it on purpose - because I did not know how clearer, in Hebrew or English (in this case it is a known word).
So I left it between a few more minor fixes, to the test version I requested earlier :)

**Comment by alesimula** [comment]
[Here it is](https://mega.nz/file/lw8izaQL#xuFVSum5AXOYOF6Jh9rpsiwTUCwBKo6r28XsSQk7JTI)

**Comment by shlomo-shlomo** [comment]
@alesimula 
https://github.com/shlomo-shlomo/wsa_pacman/commit/77cf8234fa0be1ced6b76a96448206fc1c389d11
https://github.com/shlomo-shlomo/wsa_pacman/commit/c9eb78d9821d67f45b8bfa5f59631bab91b722a6
I fixed some small things, now it's good! 🙂
By the way, when I installed in Windows Server 2016, it did not inform me that it was not supported on Windows 10 - rather the software crashed immediately at startup.
In Windows 10 PRO this is fine.

**Comment by alesimula** [comment]
@shlomo-shlomo weird... Not sure it's worth the trouble of setting up a virtual machine to troubleshoot it since it's not supported anyway

**Comment by alesimula** [comment]
v1.2.3 has been released 🎉

**Comment by shlomo-shlomo** [comment]
@alesimula I also created an updated tutorial video about the software in Hebrew :)
https://youtu.be/bra7vqG1Kvg
