### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by ABOATDev** [alesimula/wsa_pacman#39]
![image](https://user-images.githubusercontent.com/30906528/149663997-408e3c8d-9f14-46d9-98d3-b579dfa1a8e1.png)
Infinite loading for install an apk 

My apk : 
https://anonfiles.com/rcP7DeBbx7/ELYZE_-_Pr_sidentielle_2022_1.1.95_apkcombo.com_apk
Official link : 
https://play.google.com/store/apps/details?id=com.lesengages.elyze
(generate by https://apkcombo.com/fr/apk-downloader/?package=com.lesengages.elyze&device=phone&arches=default&sdkInt=default&expanded=1&format=apk&dpi=480&lang=fr) 

Its a french app

Thanks !

**Comment by alesimula** [comment]
@ABOATDev Hmm it's working for me.

![image](https://user-images.githubusercontent.com/3057584/149665978-c12c0ea8-2888-4480-8e99-c0864d1d8c13.png)

Are you sure the file is not corrupted? have you tried downloading it again?

**Comment by alesimula** [comment]
@ABOATDev Actually nevermind, this is apparently related to [this issue](https://github.com/alesimula/wsa_pacman/issues/31);

I'm closing this as a duplicate but linking this there
