### ISSUE TITLE
apk icons 

### ISSUE THREAD

**Issue by crocer211** [alesimula/wsa_pacman#4]
would it be possible to have the apk files icons be the same as what it would be on a normal android and if its possible to add desktop shortcuts to installed apps as i personally like this over wsatools

**Comment by alesimula** [comment]
@crocer211 The biggest issue would be that getting the icon is a very costly operation (Android probably has a more optimized way to do this), so doing this for every .apk file that could potentially be on your desktop or your download folder would just hog your CPU and potentially slow down your programs; it's not as straightforward as decoding an image

As for the desktop shortcut option, I like the idea, I might implement it
