### ISSUE TITLE
App version information truncated

### ISSUE THREAD

**Issue by akuropka** [alesimula/wsa_pacman#41]
I noticed that the app version is truncated due to any reason... maybe some characters (`|`)need to be escaped?
![20220121_112814_explorer](https://user-images.githubusercontent.com/22570574/150513458-e660a7f1-2041-4e9d-a5cb-46912a82997f.png)

**Comment by alesimula** [comment]
@akuropka Ah yeah I did that on purpose to fit the text

**Comment by akuropka** [comment]
Thank you for your information… no issue since it’s intended.
