### ISSUE TITLE
[BUG] Wrong automatic language

### ISSUE THREAD

**Issue by martinet101** [alesimula/wsa_pacman#45]
Language changed to arabic (it changed automatically - i have no idea of arabic)

I solved it with google lens, but just to let you know that the following locale perferences (the ones in my pc):
 - Catalan
 - Spanish (Spain)
 - English (UK)
 - Italian (Italy)
 - French (France)
 
Just led to arabic being set as the default language.

**Comment by alesimula** [comment]
@martinet101 What version are you using?

**Comment by martinet101** [comment]
Ok, yes, i though i was running the latest but I didn't Sorry for wasting your time :(

**Comment by alesimula** [comment]
@martinet101 no worries, I immediately recognized the bug as it was a stupid mistake I made (it picked the first locale from alphabetical order as fallback language)
