### ISSUE TITLE
Option for creating desktop shortcut for apps which cannot be launched independently

### ISSUE THREAD

**Issue by akuropka** [alesimula/wsa_pacman#48]
Depending if an app can be launced by its own there's an option to open the app after installation.
The option for creating a desktop shortcut should be handled in the same way as it would not make a sense to create a shortcut for an app which cannot be launched that way...

![20220130_141403_WSA-pacman](https://user-images.githubusercontent.com/22570574/151701392-af1f45a2-9b6d-416e-a107-4131b04593b7.png)

**Comment by alesimula** [comment]
@akuropka The reason I kept this option anyway is that for some apps, [as reported in this stackoverflow question](https://stackoverflow.com/questions/45440947/aapt-dump-badging-of-apk-does-not-list-any-launchable-activity-for-activity-alia), aapt.exe does not report any launchable-activity, even though there is one.

This is a minor problem for launching the app as you can just launch it later anyways, but for creating a shortcut I prefer to give it the benefit of the doubt and keep the option there

**Comment by akuropka** [comment]
Okay, just thought it would be inconsistent…
