### ISSUE TITLE
Adding more languages including Arabic

### ISSUE THREAD

**Issue by muhammadbahaa2001** [alesimula/wsa_pacman#5]
I hope in the future you add more language including Arabic.
I am ready to help you to add Arabic language translation if you agreed 🤝

**Comment by alesimula** [comment]
Hi, maybe I'll add them when I think I'm done implementing most of the features, I'll keep this issue open for now

**Comment by wcxu21** [comment]
Happy New Year!
Thank you for your work, I can help you translate the simplified Chinese language.

**Comment by alesimula** [comment]
@muhammadbahaa2001 @wcxu21 I added support for localization; Now all it's needed is adding a file inside the 'locale' directory (the "@@locale" property indicates the language)

**Comment by wcxu21** [comment]
Chinese translation has been added.

You can change the corresponding name according to your needs, thank you for your work.

**Comment by Gimmeursocks** [comment]
Added arabic support, hope right-to-left languages are shown correctly.

**Comment by Gimmeursocks** [comment]
i dont know how to use github doe :) so here is the source code, sorry

    {
    "@@locale": "ar",
    "@locale_desc": {"description": "Full name of the locale in the corresponding language"},
    "locale_desc": "العربية",
    "@locale_system": {"description": "Describes the system locale"},

    "locale_system": "النظام",

    "btn_boot": "تشغيل",
    "btn_switch_on": "مفعل",
    "btn_switch_off": "مغلق",


    "winver_10": "ويندوز 10",
    "winver_older": "إصدار ويندوز أقدم",


    "status_unsupported": "حزمة WSA غير مثبتة",
    "status_unsupported_desc": "تم العثور على إصدار {windowsVersion} و لم يثبت WSA ; و هذا التطبيق يعتمد على WSA, و التي تثبت على ويندوز 11 فقط",
    "@status_unsupported_desc" : {"placeholders": {"windowsVersion": {"type": "String"}}},
    "status_missing": "حزمة WSA غير مثبتة",
    "status_missing_desc": "حزمة WSA غير موجودة; و هذا التطبيق يعتمد على WSA, برجاء تحميل نظام اندرويد لويندوز او متجر امازون من متجر مايكروسوفت",
    "status_unknown": "جاري الاتصال",
    "status_unknown_desc": "في انتظار الاتصال بWSA",
    "status_starting": "جاري التشغيل",
    "status_starting_desc": "جاري تشغيل WSA, برجاء الانتظار",
    "status_arrested": "غير مفعل",
    "status_arrested_desc": "WSA غير مفعل",
    "status_offline": "غير متصل",
    "status_offline_desc": "لم يمكن الاتصال بWSA: يمكن ان يكون وضع المطور غير مفعل, او تم تحديد المخرج الخاطىء",
    "status_disconnected": "لا يمكن الاتصال",
    "status_disconnected_desc": "لا يمكن عمل اتصال لWSA لاسباب غير معلومه",
    "status_connected": "متصل",
    "status_connected_desc": "تم الاتصال بنجاح",


    "screen_wsa": "مدير حزم الWSA",
    "screen_settings": "الضبط",


    "wsa_manage": "إدارة الاندرويد",
    "wsa_manage_app": "إدارة التطبيقات",
    "wsa_manage_settings": "إدارة الضبط",

    "settings_port": "مدخل الWSA",
    "settings_ip": "عنوان الIP الخاص بWSA",
    "settings_autostart": "تفعبل تلقائي لWSA قبل التثبيت",
    "settings_language": "اللغة",


    "theme_mode": "وضع السمات",
    "theme_mica": "شفافية النافذة",
    "theme_icon_adaptive": "ايقونات متكيفة",


    "installer_message": "هل تريد تثبيت هذا التطبيق؟",
    "installer_installing": "جاري تثبيث {appTitle}...",
    "@installer_installing" : {"placeholders": {"appTitle": {"type": "String"}}},
    "installer_installed": "تم تثبيت {appTitle} بنجاح",
    "@installer_installed" : {"placeholders": {"appTitle": {"type": "String"}}},
    "installer_fail": "لم يتم تثبيت {appTitle}",
    "@installer_fail" : {"placeholders": {"appTitle": {"type": "String"}}},
    "installer_error_nomsg": "فشل التثبيت, لكن بلا أخطاء",
    "installer_btn_starting": "يتم التشغيل...",
    "installer_btn_loading": "تحميل...",
    "installer_btn_cancel": "إلغاء",
    "installer_btn_install": "تثبيت",
    "installer_btn_reinstall": "إعادة التثبيت",
    "installer_btn_update": "تحديث",
    "installer_btn_downgrade": "الرجوع إلى إصدار قديم(غير آمن)",
    "installer_btn_dismiss": "تم",
    "installer_btn_open": "فتح التطبيق",
    "installer_btn_checkbox_shortcut": "عمل اختصار على سطح المكتب",


    "android_permission_none": "لا يطلب اي اذونات",
    "android_permission_admin": "يدير الجهاز كمشرف",
    "android_permission_admin_brick": "يلغي تفعيل الجهاز او يعيد ضبطه عن بعد",
    "android_permission_admin_lock": "قفل الجهاز عن بعد",
    "android_permission_storage": "الملفات و الوسائط",
    "android_permission_microphone": "الميكروفون",
    "android_permission_camera": "الكاميرا",
    "android_permission_location": "الموقع",
    "android_permission_phone": "الهاتف",
    "android_permission_call_log": "سجلات المكالمات",
    "android_permission_sms": "الرسائل",
    "android_permission_contacts": "جهات الاتصال",
    "android_permission_calendar": "التقويم",
    "android_permission_activity_recognition": "الانشطة البدنية",
    "android_permission_sensors": "مستشعرات الجهاز",
    "android_permission_sensors_body": "مستشعرات البدن",
    "android_permission_nearby_devices": "تحديد الاجهزة القريبة"
    }`

**Comment by alesimula** [comment]
@Gimmeursocks it's fine thanks for the translation; I'll check later this evening, might send some screenshots here to confirm it's displayed correcrly

**Comment by alesimula** [comment]
@Gimmeursocks It's not very polished out of the box, but at least it's not completely broken either (just a bit)... might need some work though

![image](https://user-images.githubusercontent.com/3057584/148690614-9587d33e-82fa-4022-a4d2-da0b81aac4ba.png)
^ main screen

![image](https://user-images.githubusercontent.com/3057584/148690656-146fd45f-e660-4b7b-a837-23e04f9fc58d.png)
^ settings

![image](https://user-images.githubusercontent.com/3057584/148690711-c3ee5674-4287-4b11-8eff-726af36d6674.png)
^ installer

**Comment by alesimula** [comment]
Also I now realize I missed a few elements I missed while localizing the app (app version, package, and all selectable options in settings [eg. Dark, Light, System theme; Squircle, Circle icon shapes...])

**Comment by Gimmeursocks** [comment]
looks so much better than i thought it would be, especially with the font, thank you for your time and for this great program.

**Comment by Gimmeursocks** [comment]
yeah both the package and version numbers are from left to right, but these are common

**Comment by alesimula** [comment]
I added a few translation entries I'd missed: [here they are](https://github.com/alesimula/wsa_pacman/commit/521282007b8b5a9efe62d69996427f75ae3fe6d6)

**Comment by alesimula** [comment]
Here is the new entries (with their final name) for previously missing translations:

```
"settings_option_generic_system": "System",
"settings_option_generic_disabled": "Disabled",

"theme_mode_dark": "Dark",
"theme_mode_light": "Light",
"theme_mica_full": "Full",
"theme_mica_partial": "Partial",
"theme_icon_adaptive_squircle": "Squircle",
"theme_icon_adaptive_circle": "Circle",
"theme_icon_adaptive_rounded_square": "Rounded Square",

"installer_info_version": "Version: {appVersion}",
"installer_info_version_change": "Version: {appVersionOld} => {appVersionNew}",
"installer_info_package": "Package: {appPackage}",
```

**Comment by muhammadbahaa2001** [comment]
"settings_option_generic_system": "النظام",
"settings_option_generic_disabled": "غير مفعل",

"theme_mode_dark": "داكن",
"theme_mode_light": "ساطع",
"theme_mica_full": "كامل",
"theme_mica_partial": "جزئي",
"theme_icon_adaptive_squircle": "مربع منحني",
"theme_icon_adaptive_circle": "دائري",
"theme_icon_adaptive_rounded_square": "مربع مستدير",

"installer_info_version": "الإصدار: {appVersion}",
"installer_info_version_change": "الإصدار: {appVersionOld} => {appVersionNew}",
"installer_info_package": "الحزمة: {appPackage}",

**Comment by muhammadbahaa2001** [comment]
`"settings_option_generic_system": "النظام",
"settings_option_generic_disabled": "غير مفعل",

"theme_mode_dark": "داكن",
"theme_mode_light": "ساطع",
"theme_mica_full": "كامل",
"theme_mica_partial": "جزئي",
"theme_icon_adaptive_squircle": "مربع منحني",
"theme_icon_adaptive_circle": "دائري",
"theme_icon_adaptive_rounded_square": "مربع مستدير",

"installer_info_version": "الإصدار: {appVersion}",
"installer_info_version_change": "الإصدار: {appVersionOld} => {appVersionNew}",
"installer_info_package": "الحزمة: {appPackage}",`

**Comment by muhammadbahaa2001** [comment]
@alesimula here it is...

"settings_option_generic_system": "النظام",
"settings_option_generic_disabled": "غير مفعل",

"theme_mode_dark": "داكن",
"theme_mode_light": "ساطع",
"theme_mica_full": "كامل",
"theme_mica_partial": "جزئي",
"theme_icon_adaptive_squircle": "مربع منحني",
"theme_icon_adaptive_circle": "دائري",
"theme_icon_adaptive_rounded_square": "مربع مستدير",

"installer_info_version": "الإصدار: {appVersion}",
"installer_info_version_change": "الإصدار: {appVersionOld} => {appVersionNew}",
"installer_info_package": "الحزمة: {appPackage}",

**Comment by wcxu21** [comment]
Updated Simplified Chinese translation

**Comment by alesimula** [comment]
@muhammadbahaa2001 @Gimmeursocks I'm going to release a better RTL interface on the next update, here's my progress:

![image](https://user-images.githubusercontent.com/3057584/149376593-7ce59389-173f-4efc-902a-8fc11d48858b.png)
![image](https://user-images.githubusercontent.com/3057584/149376644-462f1b6e-2c94-41ce-9485-cd098fd0e33e.png)
![image](https://user-images.githubusercontent.com/3057584/149376737-3b36ea61-0109-4305-996f-cd0c44223773.png)

**Comment by muhammadbahaa2001** [comment]
@alesimula Your work is incredible and wonderful!
well done bro, thank you for listening for the feedback / request.

**Comment by Gimmeursocks** [comment]
thank you for your continued support for including arabic, have a pleasant evening.

**Comment by alpoz11** [comment]
> I hope in the future you add more language including Arabic.
> I am ready to help you to add Arabic language translation if you agreed 🤝
>
