### ISSUE TITLE
Auto Turnoff feature

### ISSUE THREAD

**Issue by rp1231** [alesimula/wsa_pacman#56]
Hi,

It would be great if there was some sort of auto turn off feature for WSA if the Pacman installer is exited and there are no other 
WSA apps running at that time.

Thanks

**Comment by alesimula** [comment]
@rp1231 WSA already does that on its own, you should just set "Subsystem resources" to "Continuous" in Windows Subsystem for Android Settings

**Comment by alesimula** [comment]
@rp1231 EDIT: I just realized I told you the opposite option, you should select "As needed", not "Continous"

**Comment by rp1231** [comment]
> @rp1231 EDIT: I just realized I typed the opposite option, you should select "As needed", not "Continous"; WSA will eventually shut down if it's not being used

Thanks for the clarification.
I thought it was a little strange 😂
