### ISSUE TITLE
The installation has failed, but no error was thrown

### ISSUE THREAD

**Issue by infinitepower18** [alesimula/wsa_pacman#58]
It is not letting me install anything on WSA.

![image](https://user-images.githubusercontent.com/44692189/154136384-2c8a297f-27c4-45af-81b2-7ae7b8210d87.png)

**Comment by hifihedgehog** [comment]
Also having this error with Windows 11 21H2 with the latest [KB5010414](https://support.microsoft.com/help/5010414) that went out today.

**Comment by hifihedgehog** [comment]
A common thread I am noticing is APKs do NOT work, but XAPKs for some reason still do.

**Comment by alesimula** [comment]
@hifihedgehog are all versions affected or just the latest?

**Comment by hifihedgehog** [comment]
I haven't tried all the versions yet. I have only tried the latest so far (1.3.0).

**Comment by hifihedgehog** [comment]
OK.

1.2.4 works fine with APK installs.

1.3.0 works fine with XAPK installs, but no longer works with APK installs.

**Comment by hifihedgehog** [comment]
@alesimula: I only tried 1.3.0 up until this point. Only XAPKs work, and not APKs.

Downgrading to 1.24, APKs work again.

**Comment by archon810** [comment]
Same issue here. https://twitter.com/ArtemR/status/1493701850716987393

**Comment by archon810** [comment]
Can confirm 1.2.4 works for me as well, but 1.3.0 does not.

**Comment by alesimula** [comment]
@archon810 yeah, I've probably done a stupid mistake as I've modified the way a separate process is executed

**Comment by alesimula** [comment]
@archon810 Well, I've fixed it :P

**Comment by infinitepower18** [comment]
Yeah I faced this too, could be a bug with the WSA

**Comment by hifihedgehog** [comment]
Thanks for fixing this so quickly, @alesimula!
