### ISSUE TITLE
[Feature suggestion] About Japanese support

### ISSUE THREAD

**Issue by Hikarutch0720** [alesimula/wsa_pacman#69]
Looking at the situation in Japan, WSAPacman is used quite a bit, and it is hoped that the app will be translated into Japanese. If you can, please do so.

**Comment by alesimula** [comment]
@Hikarutch0720 Hi, I'd love to add Japanese to my app bit i need some contribution as I don't know Japanese myself.

In the locale folder of the project there is a file for each language, which contains all the translated text (you can use en.arb as an example);

**Comment by Hikarutch0720** [comment]
[Japanese.pdf](https://github.com/alesimula/wsa_pacman/files/8310814/Japanese.pdf)
Please refer to this.  Only hiragana and katakana are used, but I can't write them here because there are so many Chinese characters.

**Comment by alesimula** [comment]
@Hikarutch0720 I need a Japanese person to translate the app by sending me a translated copy of [this file](https://github.com/alesimula/wsa_pacman/blob/main/locale/en.arb), best I can do is use google translate

**Comment by Hikarutch0720** [comment]
I think Google Translate is probably the best way to go.  Thank you.

**Comment by alesimula** [comment]
@Hikarutch0720 I added Japanese and released version 1.3.3
