### ISSUE TITLE
Automatically start subsystem when clicking install 

### ISSUE THREAD

**Issue by ishid4** [alesimula/wsa_pacman#7]
This would be great to start when clicking install if the subsystem isn't started yet. Just like opening an android app without starting the subsystem.

**Comment by alesimula** [comment]
@ishid4 I added an option to auto-start WSA when opening the package installer, as well as a button to start it in the main menu in case it's powered-off, hope everything works :P

**Comment by ishid4** [comment]
Yep, It's working fine for me. Great work!
