### ISSUE TITLE
Application management does not open

### ISSUE THREAD

**Issue by ShlomoCode** [alesimula/wsa_pacman#82]
Hello, Recently the application management button is not responding - the system is on, I press and nothing happens.
The Settings Manager button works great.
WSA Version: 2203.40000.1.0
[With Google Play services](https://github.com/LSPosed/MagiskOnWSA) ("full").
Windows version: Windows 11 Pro (21H2), 22000.613
Language: Hebrew

**Comment by ShlomoCode** [comment]
After updating the WSA version to the latest version (released today), it worked out.

**Comment by GDVeteran** [comment]
did not work😭
