### ISSUE TITLE
Chinese text mess

### ISSUE THREAD

**Issue by wenmin92** [alesimula/wsa_pacman#9]
<img src="https://user-images.githubusercontent.com/6901815/147245053-7e1cc8c3-e859-4481-ad15-960919be7d08.png" width="500px">
<img src="https://user-images.githubusercontent.com/6901815/147245055-d7ba41b5-e6ba-4703-83df-3cc08201ac3e.png" width="500px">
<img src="https://user-images.githubusercontent.com/6901815/147245060-3a6074a6-9f33-44d8-8e0c-fee5c99a20b3.png" width="500px">

**Comment by alesimula** [comment]
I guess you installed a Chinese app

**Comment by wenmin92** [comment]
> I just noticed the rectangle character, can you confirm that is the problem you are referring to? Can you share a link to that apk so i can test it?

Of course, I have installed several Chinese apps that have this problem, here I give a link to one of them for you to test.
https://static.beingfine.cn/apk/is_cool_qlisten_2.2.515261710003.apk

**Comment by alesimula** [comment]
@wenmin92 I see it a tad more messy than you do

![image](https://user-images.githubusercontent.com/3057584/147372902-5cf95420-22fc-43f4-aa77-b1fed0bd08e1.png)

**Comment by alesimula** [comment]
@wenmin92 Can you confirm this is the correct title?

![image](https://user-images.githubusercontent.com/3057584/147373156-f3fbe8d6-90c6-4d1d-b120-e881cd2a1a42.png)

**Comment by wenmin92** [comment]
> @wenmin92 I may have fixed it, this seems like the correct title.

Great, this is the correct title. Thanks!

**Comment by alesimula** [comment]
@wenmin92 Could you test it with some apps and confirm it works? https://mega.nz/file/MxchmIjJ#1uIYHcF5F7Siv_v8iQmlN-PADtkut9xrXA29kjI18ww

**Comment by wenmin92** [comment]
> @wenmin92 Could you test it with some apps and confirm it works? https://mega.nz/file/MxchmIjJ#1uIYHcF5F7Siv_v8iQmlN-PADtkut9xrXA29kjI18ww

It looks fine for install Chinese apks.

Note:
1. I also encountered a stuck interface during the installation process, and after about 2 to 4 minutes, I was able to move on to the next interface. 
2. After the installation was completed, it asked for a reboot.
3. And after I rebooted, I found that the file association was not normal.
4. The whole installation process changed a lot of files and registry, mostly related to vcredist, and my computer already has the required vcredist environment, so I don't think it should overwrite the them again.

**Comment by alesimula** [comment]
@wenmin92 The installer installs the version I bundled (wsa_pacman/installer/redist/VC_redist.x64.exe) if there is no version installed or the currently installed version is inferior to the one I bundled.

Also what do you mean by "the file association was not normal"?

**Comment by wenmin92** [comment]
1. When I double-click a apk file, the system pops up the following prompt box:

![image](https://user-images.githubusercontent.com/6901815/147386526-0930588e-4464-49a9-af9e-e54db24a8c39.png)

该文件没有与之关联的应用来执行该操作。请安装应用，若已经安装应用，请在“默认应用设置"页面中创建关联。
The file does not have an application associated with it to perform this action. Please install the application, or if you have already installed the application, create an association in the Default Application Settings screen.

2. The apk file property dialog:

<img src="https://user-images.githubusercontent.com/6901815/147386621-5e4d93b1-b96c-4a61-a00a-4fb10df3219b.png" width=500>

3. After click the `Change(C)...` button:

![image](https://user-images.githubusercontent.com/6901815/147386677-f2af64e1-b7f8-4b4c-bf1a-ee50cf2a84c5.png)

**Comment by wenmin92** [comment]
The situation mentioned in the previous post happened when there was no **reboot**.
I tried again, after uninstalling and reinstalling, there was no prompt to reboot the system, at this point, the file association was faulty, and the problem disappeared after **reboot**.

**Comment by wenmin92** [comment]
Please ignore the installation problem, this minor problem is perfectly acceptable at this stage.

**Comment by alesimula** [comment]
@wenmin92 All right, BTW could you please open a new issue for the installation problem as I'm closing this one, so it's easier to keep track of it
