### ISSUE TITLE
[ISSUE] app closes as soon as it opens

### ISSUE THREAD

**Issue by R-Rajaneesh** [alesimula/wsa_pacman#97]
I installed Google playstore from apkmirror, and it installed successfully, but when I opened it, the GUI showed up for a split second and then closed, only the amazon appstore opens properly.

Please look into this issue

![image](https://user-images.githubusercontent.com/75080457/189257399-6c3d18f9-a642-434e-88b0-dbe6282cfc7a.png)

**Comment by R-Rajaneesh** [comment]
@alesimula

**Comment by alesimula** [comment]
@R-Rajaneesh This is just an installer and the Play Store app was installed correctly; However, this is a WSA issue, and the Play Store is not officially supported by WSA.

You have a few alternatives, you can either install the [AuroraStore](https://auroraoss.com), which is a third-party Play Store client, or build and install [MagiskOnWSA](https://github.com/LSPosed/MagiskOnWSALocal), which is an unofficial WSA build with Google Apps support and Magisk root

**Comment by R-Rajaneesh** [comment]
ok thanks!!
