### ISSUE TITLE
Does not work on latest Windows 11 22H2 with WSA

### ISSUE THREAD

**Issue by ialhabbal** [alesimula/wsa_pacman#99]
Installing app does nothing.

**Comment by Makarov-Leonid** [comment]
windows 11 22H2

When the install window appears, the install button is disabled.

**Comment by reviloy** [comment]
Having the same issue.

**Comment by maxkingmax** [comment]
Same trouble！

**Comment by RUVENSHA** [comment]
When will a revised version be released?

**Comment by chenks** [comment]
same problem here.

**Comment by Largo** [comment]
It does work.

Windows Button > Search for Android > Developer > Turn on Developermode

**Comment by sm64onlydude** [comment]
> It does work.
> 
> Windows Button > Search for Android > Developer > Turn on Developermode

doesnt work for me.

**Comment by gmnowels** [comment]
> > It does work.
> > Windows Button > Search for Android > Developer > Turn on Developermode
> 
> doesnt work for me.
not my 22h2

**Comment by alesimula** [comment]
I'll take a look

**Comment by alesimula** [comment]
Guys it's strangely working for me... can you tell me the WSA version? (Android Subsystem for Android Settings -> About -> Version [on the bottom] )

**Comment by sm64onlydude** [comment]
version 2207.40000.8.0

**Comment by sm64onlydude** [comment]
thats strange, it works now. Idk bout the other 2 people, but it is working
for me again. Dont know how or why

**Comment by sm64onlydude** [comment]
right as i sent this unknown error gets thrown at me

**Comment by RUVENSHA** [comment]
You did something for it to work
Or is it a matter of luck
Of course developer mode is enabled
For me it only worked after I ran ADB
But it stuck my WSA so I removed it

**Comment by maxkingmax** [comment]
> version 2207.40000.8.0



> Guys it's strangely working for me... can you tell me the WSA version? (Android Subsystem for Android Settings -> About -> Version [on the bottom] )

version 2207.40000.8.0

**Comment by RUVENSHA** [comment]
Started working today
After I updated the Windows version today it worked again

**Comment by RUVENSHA** [comment]
Windows 11 Pro
22621.675

**Comment by mehdieft95** [comment]
Seems WSA Developer Mode is not detecting PacMan's request. The following fixed the grayed out "Install" button for me:

- Restart your system
- Open PacMan app and make sure it is connected to WSA (Green "Connected" Checkmark)
- Open WSA app and go to "Developer" tab
- Turn off "Developer mode" and wait 10 second
- Turn it back on and it should ask you to allow/deny PacMan requests to USB debug
- Click "Allow"

You should be able to install your APK files now. Below are my build info:

OS:         22621.675
WSA:      2207.40000.8.0
PacMan: 1.3.6

**Comment by vadimkantorov** [comment]
Same issue. PacMan shows itself well connected to WSA, but the Install button is disabled, and "Manage applications" does nothing on click either.

**Comment by alesimula** [comment]
@mehdieft95 I added an FAQ section in the README and linked your comment, BTW checking the "always allow" box before clicking allow would avoid having to repeat this hassle (I took the liberty to edit your response 😅)

I'm not sure whether this also happens on new installations, or on older WSA PacMan installations after Microsoft updated the way USB debugging authorizations are managed

**Comment by danielhuvr** [comment]
I had the same issue on a fresh WSA Pacman installation and restarting the computer and android substack rectified the issue. Should have known to reboot when things weren't working as expected after installing any application.

**Comment by vEonz121** [comment]
> It does work.
> 
> Windows Button > Search for Android > Developer > Turn on Developermode

Missing. doesnt not appear. Amazon appstore is installed.

**Comment by XP1** [comment]
You need to enable developer mode in Windows Subsystem for Android™️ or WsaSettings.exe ("C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_2310.40000.2.0_x64__8wekyb3d8bbwe\WsaSettings.exe").

Enabling developer mode in Android settings (clicking Build number 7 times) will not work.

![WSA PacMan developer mode](https://github.com/alesimula/wsa_pacman/assets/776585/fe17174b-e9a5-4360-804e-8b59becd1294)
